language: node_js
dist: trusty
node_js:
  - "8.0.0"
services:
  - mysql
env:
  global:
    - PORT=3000
    - DATABASE_HOST=localhost
    - DATABASE_USER=root
    - DATABASE_NAME=subito_test
    - ENCRYPTION_KEY=test_key_123
    - ADMIN_AUTH_SECRET=helloworld
    - TEST_CONSOLE_LOGGING=true
addons:
  mysql: "5.7.19"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS subito_test;'
install:
  - npm install
  - npm install -g swagger
before_script:
  - mysql -D subito_test < ddl/ddl.sql
  - npm run migrate-up:local
  - npm run migrate-up:test
script:
  - npm run eslint
  - npm run coverage
  - npm run test
