language: node_js
dist: trusty
node_js:
  - "8.0.0"
services:
  - mysql
env:
  global:
    - PORT=3000
    - DATABASE_HOST=localhost
    - DATABASE_USER=root
    - DATABASE_NAME=subito_test
addons:
  mysql: "5.7.19"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS subito_test;'
install:
  - npm install
before_script:
  - mysql -D subito < ddl/ddl.sql
script:
#  - ./node_modules/.bin/eslint-changes
  - npm run test
