swagger: "2.0"
info:
  version: "2.0.0"
  title: Subito Slash Service
  description: a service for getting soup data from [Subito](http://www.subitosoups.com/) in Indianapolis
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /subito
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /slack:
    x-swagger-router-controller: slackController
    post:
      description: handles and pipes all Slack slash commands
      operationId: handleSlack
      tags:
        - Slack
      parameters:
        - name: body
          in: body
          description: a generic Slack post body
          required: true
          schema:
            required:
              - text
              - token
            properties:
              token:
                type: string
                description: a Slack integration token to be validated against
              text:
                type: string
              team_id:
                type: string
              team_domain:
                type: string
              channel_id:
                type: string
              channel_name:
                type: string
              user_id:
                type: string
              user_name:
                type: string
              command:
                type: string
              response_url:
                type: string 
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SlackResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /day:
    # binds a127 app logic to a route
    x-swagger-router-controller: soupCalendarController
    get:
      description: get the soups for today
      # used as the method name of the controller
      operationId: getSoupsForToday
      tags:
        - SoupCalendar
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SoupCalendarViewObject"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /day/{day}:
    # binds a127 app logic to a route
    x-swagger-router-controller: soupCalendarController
    get:
      description: get the soups for a day
      # used as the method name of the controller
      operationId: getSoupsForDay
      tags:
        - SoupCalendar
      parameters:
        - name: day
          in: path
          description: "the day to get soups for :: example - tomorrow | 12-08-2017"
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SoupCalendarViewObject"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /all:
    x-swagger-router-controller: soupCalendarController
    get:
      description: Gets the fully stored soup calendar
      operationId: getAllSoups
      tags:
        - SoupCalendar
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/SoupCalendarViewObject"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /subscribe:
    x-swagger-router-controller: subscriberController
    post:
      description: Subscribe to daily (weekday) notifications
      operationId: subscribe
      tags:
        - Subscribe
      parameters:
        - name: body
          in: body
          description: subscription request body
          required: true
          schema:
            required:
              - slackUserId
            properties:
              slackUserId:
                type: string
              slackUsername:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /unsubscribe:
    x-swagger-router-controller: subscriberController
    post:
      description: Unsubscribe to daily (weekday) notifications
      operationId: unsubscribe
      tags:
        - Subscribe
      parameters:
        - name: body
          in: body
          description: unsubscribe request body
          required: true
          schema:
            $ref: "#/definitions/UnsubscribeBody"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Unsubscribe to daily (weekday) notifications
      operationId: unsubscribe2
      tags:
        - Subscribe
      parameters:
        - name: body
          in: body
          description: unsubscribe request body
          required: true
          schema:
            $ref: "#/definitions/UnsubscribeBody"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /search:
    x-swagger-router-controller: soupCalendarController
    get:
      description: Search for soup availability
      operationId: search
      tags:
        - Search
        - SoupCalendar
      parameters:
        - name: search
          in: query
          description: a soup search string
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/SoupCalendarObject"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SoupCalendarViewObject:
    type: object
    properties:
      text:
        type: string
      day:
        type: string
        format: date
      soups:
        type: array
        items:
          type: string
      soupsStr:
        type: string
  SoupCalendarObject:
    type: object
    required:
      - day
      - soup
    properties:
      day:
        type: string
        format: date
      soup:
        type: string
  UnsubscribeBody:
    type: object
    properties:
      id:
        type: number
      slackUserId:
        type: string
      slackUsername:
        type: string
  SlackResponse:
    type: object
    required:
      - text
    properties:
      text:
        type: string
        description: a Slack formatted message string
  SuccessResponse:
    required:
      - text
    properties:
      text:
        type: string
        description: a Slack formatted message string
  ErrorResponse:
    required:
      - text
    properties:
      text:
        type: string
        description: a Slack formatted message string
