swagger: "2.0"
info:
  version: "0.0.1"
  title: Subito Slash Service
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /subito:
    # binds a127 app logic to a route
    x-swagger-router-controller: soupCalendarController
    post:
      description: get the soups for a day
      # used as the method name of the controller
      operationId: getSoupsForDay
      parameters:
        - name: body
          in: body
          description: the day to get soups for
          required: false
          schema:
            properties:
              day:
                type: string
                format: date
                example: 'MM/DD/YYYY'
              token:
                type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SoupCalendarViewObject"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /subito/all:
    x-swagger-router-controller: soupCalendarController
    get:
      description: Gets the fully stored soup calendar
      operationId: getAllSoups
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/SoupCalendarViewObject"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SoupCalendarViewObject:
    type: object
    required:
      - day
      - soups
    properties:
      day:
        type: string
        format: date
      soups:
        type: array
        items:
          type: string
      soupsStr:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
